services:
  mysql:
    image: mysql:8.0
    container_name: onco_sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - onco_network

  minio:
    image: minio/minio
    container_name: onco_minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - ./volumes/minio:/data
    networks:
      - onco_network

  mongodb:
    image: mongo:8.2.1
    container_name: onco_mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - ./volumes/mongo:/data/db
    networks:
      - onco_network

  rest:
    image: localhost:5000/sae-rest:latest
    container_name: onco_rest
    environment:
      PORT: ${PORT}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      S3_HOST: "${S3_HOST}"
      S3_PORT: ${S3_PORT}
      S3_USER: ${S3_USER}
      S3_PASSWORD: ${S3_PASSWORD}
      SQL_HOST: ${SQL_HOST}
      SQL_PORT: ${SQL_PORT}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_DATABASE: ${SQL_DATABASE}
      VIRTUAL_HOST: sae-api.jdsr.dev
      VIRTUAL_PORT: 8000
      SSL_CERTIFICATE: /ssl/sae-api.jdsr.dev/fullchain.pem
      SSL_CERTIFICATE_KEY: /ssl/sae-api.jdsr.dev/privkey.pem
    depends_on:
      - mongodb
      - minio
      - mysql
    networks:
      - onco_network

  web:
    image: localhost:5000/sae-app:latest
    container_name: onco_web
    environment:
      VIRTUAL_HOST: sae.jdsr.dev
      VIRTUAL_PORT: 5173
      API_URL: ${API_URL}
    depends_on:
      - rest
    networks:
      - onco_network

networks:
  onco_network:
    name: onco_network
    driver: bridge
