services:

  minio:
    image: minio/minio
    container_name: onco_minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: butinfo-vitrygtr
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./volumes/minio:/data
    networks:
      - onco_network

  mongodb:
    image: mongo:8.2.1
    container_name: onco_mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=butinfo
      - MONGO_INITDB_DATABASE=onco_vision
    volumes:
      - ./volumes/mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - onco_network
  segmenter:
    build:
      context: ../segmenter
      dockerfile: Dockerfile
    container_name: segmenter
    ports:
      - "7000:7000"
    restart: unless-stopped

networks:
  onco_network:
    name: onco_network
    driver: bridge